"""add_revoked_at_to_refresh_tokens

Revision ID: 2955404a34d7
Revises: ca08251cbc81
Create Date: 2026-04-11 15:40:30.182442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2955404a34d7'
down_revision: Union[str, Sequence[str], None] = 'ca08251cbc81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'revoked_at')
    # ### end Alembic commands ###
