"""add role to users

Revision ID: 62f091a74a10
Revises: b1c2d3e4f5a6
Create Date: 2026-04-20 23:48:34.740335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62f091a74a10'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_reports_no_duplicate_pending'), table_name='reports', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index(op.f('idx_reports_status_created'), table_name='reports')
    op.drop_index(op.f('idx_reports_target'), table_name='reports')
    op.drop_index(op.f('idx_sticker_title'), table_name='sticker_library', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('trade_requests', 'offered_post_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Ordered list of post IDs the requester offers; null means no specific posts offered',
               existing_nullable=True)
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default=sa.text("'user'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.alter_column('trade_requests', 'offered_post_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Ordered list of post IDs the requester offers; null means no specific posts offered',
               existing_nullable=True)
    op.create_index(op.f('idx_sticker_title'), 'sticker_library', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_reports_target'), 'reports', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('idx_reports_status_created'), 'reports', ['status', 'created_at'], unique=False)
    op.create_index(op.f('idx_reports_no_duplicate_pending'), 'reports', ['reporter_id', 'target_type', 'target_id'], unique=True, postgresql_where="((status)::text = 'pending'::text)")
    # ### end Alembic commands ###
