"""add_trade_requests

Revision ID: eb5703a6fa90
Revises: a1f3c8e02b47
Create Date: 2026-04-06 22:30:42.606519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5703a6fa90'
down_revision: Union[str, Sequence[str], None] = 'a1f3c8e02b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('requester_id', sa.BigInteger(), nullable=False),
    sa.Column('recipient_id', sa.BigInteger(), nullable=False),
    sa.Column('target_post_id', sa.BigInteger(), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('offered_folder_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=10), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("request_type IN ('WANT_TO_TRADE', 'HAVE_WHAT_YOU_NEED')", name='ck_trade_request_type'),
    sa.CheckConstraint("status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED')", name='ck_trade_request_status'),
    sa.ForeignKeyConstraint(['offered_folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trade_requests_decline_count', 'trade_requests', ['requester_id', 'recipient_id'], unique=False, postgresql_where=sa.text("status = 'DECLINED'"))
    op.create_index('idx_trade_requests_pending_unique', 'trade_requests', ['requester_id', 'target_post_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index('idx_trade_requests_recipient_pending', 'trade_requests', ['recipient_id', 'created_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index('idx_trade_requests_requester', 'trade_requests', ['requester_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trade_requests_requester', table_name='trade_requests')
    op.drop_index('idx_trade_requests_recipient_pending', table_name='trade_requests', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index('idx_trade_requests_pending_unique', table_name='trade_requests', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index('idx_trade_requests_decline_count', table_name='trade_requests', postgresql_where=sa.text("status = 'DECLINED'"))
    op.drop_table('trade_requests')
    # ### end Alembic commands ###
