-- Stub for the test DB only.
-- In production, public.users is owned by the Python backend (Alembic).
-- The messaging service reads it as a cross-service reference; this stub
-- satisfies Hibernate validation and lets UserRepository queries run in the
-- isolated messaging test DB.
CREATE TABLE IF NOT EXISTS public.users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    email         VARCHAR(50)  NOT NULL UNIQUE,
    password_hash TEXT         NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    avatar_path   VARCHAR(255),
    bio           VARCHAR(500),
    sticker_count INTEGER      NOT NULL DEFAULT 0
);
